### ISSUE TITLE
Error 'Missing Javadoc comment'

### ISSUE THREAD

**Issue by raulvj** [raulvj/iso2-bank_A02#13]
The responsible for this issue will be @EnriqueRV501. 

Enrique, you will be on charge of adding the requested documentation for Javadoc wherever is needed. In order to do that, it would be recommended that you take a look at the **Checkstyle report** and search for errors which category is _Javadoc_ . In this report you will find the file and the line in which the error is located.

Good luck!

**Comment by EnriqueRV501** [comment]
The problems caused by the JavadocMethods, JavadocVariable and JavadocStyle have been mostly resolved, you can see it in this commit: https://github.com/raulvj/iso2-bank_A02/commit/7be2bfb93d2e90d83c05e81abdb3470fecbf89a3

JavadocMethods have been resolved creating the corresponding method Javadocs.
Every method has all the used parameters described, along the variables it should return (if it returns something) and the description of each Exception.

In addition, every new bug caused by these changes have been resolved.

**Comment by EnriqueRV501** [comment]
We had a problem because the pull request made by José and my pull request were conflicting each other, therefore, we had to resolve these conflicts by hand.
The commit related to this issue is: 1c8c35b
