### ISSUE TITLE
FindBugs report

### ISSUE THREAD

**Issue by raulvj** [raulvj/iso2-bank_A02#14]
The responsible for this issue will be @Aharon1377 .

Aaron, you will be on charge of solving the bugs that appears in this [report](https://drive.google.com/file/d/1UxMvwMqNyVq4u08WKY2RluD-vvLA6Quk/view?usp=sharing). As you already know, this tool provide us the total number of bugs within the different classes alongside the information about them (bug, category, line and priority) 

There is a total of 7 bugs that you will try to deal with, but most of them are located in **Manager** , so try to focus on this class.

Good luck!

**Comment by AaronRBG** [comment]
The Findbugs' errors have been solved completely, you can see it in this commit: https://github.com/raulvj/iso2-bank_A02/commit/5c5b5e9a2fb4e1cae5a78442956c9e96b199a21d

The Cuenta bug was solved by changing an inefficient constructor by a more efficient method.

The Manager bugs were fixed by creating setters, so that the static variables are not accessed directly by a method.

In addition, some checkstyle bugs were created while solving these bugs. Those checkstyle bugs were also fixed in the attached commit.

**Comment by EnriqueRV501** [comment]
We had a problem because the pull request made by José and my pull request were conflicting each other, therefore, we had to resolve it merging them by hand.
The commit related to this issue is: https://github.com/raulvj/iso2-bank_A02/commit/1c8c35b16f14df07f87b25ffeb68549c45897725

**Comment by AaronRBG** [comment]
We had a problem because the pull request made by José, the one made by Enrique and my pull request were conflicting each other, therefore, we had to resolve these conflicts by hand.
The commit related to this issue is: https://github.com/raulvj/iso2-bank_A02/commit/e1133a8f5874228724b518f41550ad82aa97f1df
