### ISSUE TITLE
Checkstyle errors

### ISSUE THREAD

**Issue by raulvj** [raulvj/iso2-bank_A02#15]
The responsible for this issue will be @JoseCalzado .

José, you will be on charge of checking the errors that appears in this [report](https://drive.google.com/file/d/14zKtybbHGnmi-BnelMIw5sJk8eqoK8oZ/view?usp=sharing). There are many errors, so you will try to focus on those which can be fixed with very little effort. 

Good luck!

**Comment by JoseCalzado** [comment]
Hi Boss!

417 checkstyle errors were defeated on my watch. You can check the commit at https://github.com/raulvj/iso2-bank_A02/commit/221505709c286f45c54a5836a67d81e8ace45863

The mayority of these errors were solved deleting some spaces and all the tabulations, like the **FileTabCharacter**, **RegExpSingleline**, **GenericWhitespace**, **WhitespaceAround** and **LineLength**.

The others like **MagicNumber** were solved creating global variables at the start of the classes with the numbers that we are going to use on the methods (like on a for, we use the number 0 to initializate the variable, so if we need it we create it like "**static final int ZERO = 0**".

The **FinalParameters** Error were solved putting each parameter of each method as a "final" variable. Meanwhile, the **HiddenField** one was an issue with the names of the parameter of certain methods, that had the exact name as a variable of the class. So we changed it, adding a number to the variable to distinguish.
							 		
The **NeedBraces** was because sometimes the  _for_ and _if_ of some methods didn't have the brackets, so we simply added it.

Finally the last error that was solved during my watch was the **VisibiliyModifier**, that was called because some variables were created as protected and it were needed to be private. The issue with this error is that in the _Tarjeta_ class, we have protected variables that doesn't have a _get_ or a _set_ method, so if we change it to private, we loose coverage on the testing part of the _Tarjeta_ class, so we have decided to not change it.


The errors that were let alive were the **HideUtilityClassConstructor**, that can be resolved by putting the _Lanzadera_ class as private, but it creates tons of errors and destroys our coverage.

The **NewlineAtEndOfFile** error has been the only error that we simply couldn't solve. We have tried some things, but we came to the conclusion that we would need to access to the configuration file of _CheckStyle_ and we don't have it, so that error is our "_Moby Dick_".

The rest of the errors that appear are for not having the javadoc comments on certain methods, but that will be my friend @EnriqueRV501 .

_Don José._
