### ISSUE TITLE
PMD report

### ISSUE THREAD

**Issue by raulvj** [raulvj/iso2-bank_A02#16]
This issue will involve two developers: @Aharon1377 @JoseCalzado

Both of you are going to work side by side on this report. There is only one error on this report that involves the _Manager_ class. As spartans would say:

**_"Come back with your shield - or on it"_**

Good luck!

**Comment by AaronRBG** [comment]
The reason why this error haven´t been fixed is because although it says that loadDAO is an UnusedPrivateMethod, the truth is that it is used internally, so the removal of this method, (which will be the standard solution for an UnusedPrivateMethod) will cause problems and destroy our project.

Don Aarón and Don José.
